<a href="https://colab.research.google.com/github/gmourazz/Atividades/blob/main/C%C3%B3pia_de_Machine_Learning_Com_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importar bibliotecas
import tensorflow as tf
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# Carregar conjunto de dados Iris
iris = load_iris()
X = iris.data
y = iris.target

In [ ]:
# Dividir os dados em treinamento e teste (80% treino, 20% teste)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
# Normalizar os dados
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:
# Construir o modelo com TensorFlow (Rede Neural Simples)
model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=(X_train.shape[1],)),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')  # 3 classes de saída
])

# Compilar o modelo
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
# Treinar o modelo
history = model.fit(X_train, y_train, epochs=50, batch_size=10, validation_split=0.2)

Epoch 1/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 2s 35ms/step - accuracy: 0.4066 - loss: 1.0663 - val_accuracy: 0.2083 - val_loss: 1.0900
Epoch 2/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3623 - loss: 1.0503 - val_accuracy: 0.2083 - val_loss: 1.0583
Epoch 3/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.3531 - loss: 1.0255 - val_accuracy: 0.2083 - val_loss: 1.0281
Epoch 4/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4419 - loss: 0.9438 - val_accuracy: 0.2500 - val_loss: 1.0035
Epoch 5/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4303 - loss: 0.9223 - val_accuracy: 0.2500 - val_loss: 0.9803
Epoch 6/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4375 - loss: 0.9091 - val_accuracy: 0.3333 - val_loss: 0.9572
Epoch 7/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.5721 - loss: 0.8608 - val_accuracy: 0.5417 - val_loss: 0.9345
Epoch 8/50
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6465 - loss: 0.8727 - val_accuracy: 0.7083 - val_los

In [ ]:
# Avaliar o modelo nos dados de teste
test_loss, test_acc = model.evaluate(X_test, y_test, verbose=2)
print(f'\nPrecisão no conjunto de teste: {test_acc:.4f}')

1/1 - 0s - 54ms/step - accuracy: 0.9333 - loss: 0.2858

Precisão no conjunto de teste: 0.9333


In [ ]:
# Fazer previsões
predictions = model.predict(X_test)

# Exibir as previsões para as primeiras 5 amostras
print("Previsões das primeiras 5 amostras de teste:")
print(predictions[:5])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
Previsões das primeiras 5 amostras de teste:
[[2.1862936e-01 4.7921833e-01 3.0215225e-01]
 [9.9142146e-01 8.0881538e-03 4.9038284e-04]
 [4.6748351e-02 1.5434107e-02 9.3781751e-01]
 [2.1760833e-01 4.0016922e-01 3.8222247e-01]
 [1.9842668e-01 3.2873815e-01 4.7283512e-01]]
